#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'


require 'strscan'

class Parser < Racc::Parser

module_eval(<<'...end parse.y/module_eval...', 'parse.y', 146)

def initialize(src)
  @ss = StringScanner.new(src)
end

def scan
  until @ss.eos?
    if (tok = @ss.scan /\s+/)
      # nothing to do
    elsif (tok = @ss.scan /,|\(|\)|\{|\}|=>|\+|\-|\*|\/|%|>|<|==|\]\s*=|\[|\]|=/)
      yield [tok, tok]
    elsif (tok = @ss.scan /"(?:[^"]|"")*"/)
      yield [:STRING, tok.slice(1...-1)]
    elsif (tok = @ss.scan /\d+/)
      yield [:NUMBER, tok.to_i]
    elsif (tok = @ss.scan /\w+/)
      yield [:IDENTIFIER, tok]
    elsif @ss.scan /#.*$/
      # nothing to do
    end
  end

  yield [false, '']
end

def parse
  yyparse self, :scan
end

def self.parse(src)
  self.new(src).parse
end
...end parse.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    23,    64,    72,    77,    64,    78,    82,     7,    20,    66,
    34,    63,    45,     8,     9,    27,    28,    25,    26,    18,
    19,    21,    65,    43,    22,    55,   nil,   nil,    29,    30,
    31,    32,   nil,   nil,    33,    27,    28,    25,    26,    80,
     7,    20,   nil,   nil,   nil,   nil,     8,     9,    29,    30,
    31,    32,    18,    19,    57,   nil,   nil,    22,    27,    28,
    25,    26,   nil,     7,    20,   nil,   nil,   nil,   nil,     8,
     9,    29,    30,    31,    32,    18,    19,    57,   nil,   nil,
    22,    27,    28,    25,    26,   nil,    37,   nil,   nil,    38,
    27,    28,    25,    26,    29,    30,    31,    32,   nil,   nil,
    33,    39,    73,    29,    30,    31,    32,   nil,   nil,    33,
    67,    27,    28,    25,    26,   nil,   nil,   nil,   nil,    27,
    28,    25,    26,   nil,    29,    30,    31,    32,   nil,   nil,
    33,    67,    29,    30,    31,    32,   nil,   nil,    33,    27,
    28,    25,    26,   nil,   nil,   nil,    27,    28,    25,    26,
   nil,   nil,    29,    30,    31,    32,    27,    28,    33,    29,
    30,    31,    32,    27,    28,    33,   nil,   nil,   nil,    29,
    30,    31,    32,   nil,   nil,    33,    29,    30,    31,    32,
   nil,   nil,    33,    27,    28,    25,    26,   nil,   nil,   nil,
    27,    28,    25,    26,   nil,   nil,    29,    30,    31,    32,
   nil,   nil,    33,    29,    30,    31,    32,   nil,   nil,    33,
    27,    28,    25,    26,   nil,   nil,   nil,    27,    28,    25,
    26,   nil,   nil,    29,    30,    31,    32,   nil,   nil,    33,
    29,    30,    31,    32,   nil,   nil,    33,    27,    28,    25,
    26,   nil,   nil,   nil,    27,    28,    25,    26,   nil,   nil,
    29,    30,    31,    32,   nil,   nil,    33,    29,    30,    31,
    32,   nil,   nil,    33,    27,    28,    25,    26,    29,    30,
    31,    32,   nil,   nil,    33,   nil,   nil,    29,    30,    31,
    32,     7,    20,    33,   nil,    69,   nil,     8,     9,   nil,
     7,    20,   nil,    18,    19,    21,     8,     9,    22,   nil,
   nil,   nil,    18,    19,    21,     7,    20,    22,   nil,    71,
   nil,     8,     9,   nil,   nil,   nil,   nil,    18,    19,    21,
     7,    20,    22,   nil,    84,   nil,     8,     9,   nil,     7,
    20,   nil,    18,    19,    21,     8,     9,    22,    20,   nil,
   nil,    18,    19,    21,    20,   nil,    22,   nil,   nil,    18,
    19,    21,    20,   nil,    22,    18,    19,    21,    20,   nil,
    22,   nil,   nil,    18,    19,    21,    20,   nil,    22,    18,
    19,    21,    41,    20,    22,    60,   nil,    18,    19,    21,
    20,   nil,    22,   nil,    18,    19,    21,    20,   nil,    22,
   nil,    18,    19,    21,    20,   nil,    22,   nil,    18,    19,
    21,    20,   nil,    22,   nil,    18,    19,    21,    20,   nil,
    22,   nil,    18,    19,    21,    20,   nil,    22,   nil,    18,
    19,    21,    20,   nil,    22,   nil,    18,    19,    21,    20,
   nil,    22,   nil,    18,    19,    21,    20,   nil,    22,   nil,
    18,    19,    21,    20,   nil,    22,   nil,    18,    19,    21,
    20,   nil,    22,   nil,    18,    19,    21,    20,   nil,    22,
   nil,    18,    19,    21,    20,   nil,    22,   nil,    18,    19,
    21,    20,   nil,    22,   nil,    18,    19,    21,   nil,   nil,
    22,   nil,    18,    19,    21,    41,   nil,    22,    29,    30,
    31,    32,   nil,   nil,    33 ]

racc_action_check = [
     1,    42,    61,    68,    61,    68,    78,     1,     1,    44,
     7,    42,    23,     1,     1,    75,    75,    75,    75,     1,
     1,     1,    44,    22,     1,    34,   nil,   nil,    75,    75,
    75,    75,   nil,   nil,    75,    36,    36,    36,    36,    75,
    36,    36,   nil,   nil,   nil,   nil,    36,    36,    36,    36,
    36,    36,    36,    36,    36,   nil,   nil,    36,    35,    35,
    35,    35,   nil,    35,    35,   nil,   nil,   nil,   nil,    35,
    35,    35,    35,    35,    35,    35,    35,    35,   nil,   nil,
    35,    62,    62,    62,    62,   nil,    20,   nil,   nil,    20,
    70,    70,    70,    70,    62,    62,    62,    62,   nil,   nil,
    62,    20,    62,    70,    70,    70,    70,   nil,   nil,    70,
    70,    54,    54,    54,    54,   nil,   nil,   nil,   nil,    83,
    83,    83,    83,   nil,    54,    54,    54,    54,   nil,   nil,
    54,    54,    83,    83,    83,    83,   nil,   nil,    83,     6,
     6,     6,     6,   nil,   nil,   nil,    40,    40,    40,    40,
   nil,   nil,     6,     6,     6,     6,    46,    46,     6,    40,
    40,    40,    40,    47,    47,    40,   nil,   nil,   nil,    46,
    46,    46,    46,   nil,   nil,    46,    47,    47,    47,    47,
   nil,   nil,    47,    50,    50,    50,    50,   nil,   nil,   nil,
    51,    51,    51,    51,   nil,   nil,    50,    50,    50,    50,
   nil,   nil,    50,    51,    51,    51,    51,   nil,   nil,    51,
    52,    52,    52,    52,   nil,   nil,   nil,    53,    53,    53,
    53,   nil,   nil,    52,    52,    52,    52,   nil,   nil,    52,
    53,    53,    53,    53,   nil,   nil,    53,    59,    59,    59,
    59,   nil,   nil,   nil,    74,    74,    74,    74,   nil,   nil,
    59,    59,    59,    59,   nil,   nil,    59,    74,    74,    74,
    74,   nil,   nil,    74,    79,    79,    79,    79,    49,    49,
    49,    49,   nil,   nil,    49,   nil,   nil,    79,    79,    79,
    79,    56,    56,    79,   nil,    56,   nil,    56,    56,   nil,
     0,     0,   nil,    56,    56,    56,     0,     0,    56,   nil,
   nil,   nil,     0,     0,     0,    58,    58,     0,   nil,    58,
   nil,    58,    58,   nil,   nil,   nil,   nil,    58,    58,    58,
    81,    81,    58,   nil,    81,   nil,    81,    81,   nil,    77,
    77,   nil,    81,    81,    81,    77,    77,    81,     8,   nil,
   nil,    77,    77,    77,    73,   nil,    77,   nil,   nil,     8,
     8,     8,    33,   nil,     8,    73,    73,    73,    21,   nil,
    73,   nil,   nil,    33,    33,    33,    37,   nil,    33,    21,
    21,    21,    21,    38,    21,    38,   nil,    37,    37,    37,
    39,   nil,    37,   nil,    38,    38,    38,    80,   nil,    38,
   nil,    39,    39,    39,     9,   nil,    39,   nil,    80,    80,
    80,    64,   nil,    80,   nil,     9,     9,     9,    66,   nil,
     9,   nil,    64,    64,    64,    25,   nil,    64,   nil,    66,
    66,    66,    26,   nil,    66,   nil,    25,    25,    25,    27,
   nil,    25,   nil,    26,    26,    26,    28,   nil,    26,   nil,
    27,    27,    27,    29,   nil,    27,   nil,    28,    28,    28,
    30,   nil,    28,   nil,    29,    29,    29,    31,   nil,    29,
   nil,    30,    30,    30,    32,   nil,    30,   nil,    31,    31,
    31,    57,   nil,    31,   nil,    32,    32,    32,   nil,   nil,
    32,   nil,    57,    57,    57,    57,   nil,    57,    48,    48,
    48,    48,   nil,   nil,    48 ]

racc_action_pointer = [
   283,     0,   nil,   nil,   nil,   nil,   137,     2,   330,   386,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    80,   350,    -2,    12,   nil,   407,   414,   421,   428,   435,
   442,   449,   456,   344,    16,    56,    33,   358,   365,   372,
   144,   nil,   -11,   nil,    -3,   nil,   154,   161,   473,   253,
   181,   188,   208,   215,   109,   nil,   274,   463,   298,   235,
   nil,    -8,    79,   nil,   393,   nil,   400,   nil,    -7,   nil,
    88,   nil,   nil,   336,   242,    13,   nil,   322,    -2,   262,
   379,   313,   nil,   117,   nil ]

racc_action_default = [
   -45,   -45,    -1,    -3,    -4,    -5,    -6,   -45,   -45,   -45,
   -12,   -13,   -14,   -15,   -16,   -17,   -18,   -19,   -28,   -29,
   -30,   -45,   -42,   -45,    -2,   -45,   -45,   -45,   -45,   -45,
   -45,   -45,   -45,   -45,   -45,   -45,   -45,   -45,   -45,   -45,
   -40,   -34,   -45,   -38,   -45,    85,   -20,   -21,   -22,   -23,
   -24,   -25,   -26,   -27,   -45,    -8,   -45,   -45,   -45,   -31,
   -32,   -45,   -45,   -35,   -45,   -39,   -45,   -36,   -45,   -10,
   -40,   -11,   -33,   -45,   -41,   -45,   -43,   -45,   -45,   -37,
   -45,   -45,    -9,   -44,    -7 ]

racc_goto_table = [
    24,     1,    35,    36,    68,    61,    44,    76,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    40,   nil,   nil,   nil,    46,
    47,    48,    49,    50,    51,    52,    53,    54,   nil,   nil,
   nil,    59,    40,    62,   nil,   nil,    56,    58,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    70,   nil,   nil,   nil,    24,   nil,    24,    74,   nil,
    75,   nil,   nil,   nil,   nil,   nil,   nil,    79,   nil,   nil,
   nil,   nil,   nil,   nil,    83,   nil,   nil,   nil,    81,   nil,
    24 ]

racc_goto_check = [
     2,     1,     6,     6,     7,    16,    17,    18,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     6,   nil,   nil,   nil,     6,
     6,     6,     6,     6,     6,     6,     6,     6,   nil,   nil,
   nil,     6,     6,     6,   nil,   nil,     1,     1,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     6,   nil,   nil,   nil,     2,   nil,     2,     6,   nil,
     6,   nil,   nil,   nil,   nil,   nil,   nil,     6,   nil,   nil,
   nil,   nil,   nil,   nil,     6,   nil,   nil,   nil,     1,   nil,
     2 ]

racc_goto_pointer = [
   nil,     1,    -1,   nil,   nil,   nil,    -6,   -51,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   -33,   -16,   -59 ]

racc_goto_default = [
   nil,   nil,     2,     3,     4,     5,     6,   nil,    10,    11,
    12,    13,    14,    15,    16,    17,    42,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 28, :_reduce_1,
  2, 28, :_reduce_2,
  1, 29, :_reduce_3,
  1, 29, :_reduce_4,
  1, 29, :_reduce_5,
  1, 29, :_reduce_6,
  7, 30, :_reduce_7,
  0, 34, :_reduce_none,
  3, 34, :_reduce_9,
  4, 31, :_reduce_10,
  4, 32, :_reduce_11,
  1, 33, :_reduce_12,
  1, 33, :_reduce_13,
  1, 33, :_reduce_14,
  1, 33, :_reduce_15,
  1, 33, :_reduce_16,
  1, 33, :_reduce_17,
  1, 33, :_reduce_18,
  1, 33, :_reduce_19,
  3, 33, :_reduce_20,
  3, 33, :_reduce_21,
  3, 33, :_reduce_22,
  3, 33, :_reduce_23,
  3, 33, :_reduce_24,
  3, 33, :_reduce_25,
  3, 33, :_reduce_26,
  3, 33, :_reduce_27,
  1, 35, :_reduce_28,
  1, 35, :_reduce_29,
  1, 36, :_reduce_30,
  3, 37, :_reduce_31,
  3, 38, :_reduce_32,
  4, 38, :_reduce_33,
  2, 39, :_reduce_34,
  3, 39, :_reduce_35,
  4, 40, :_reduce_36,
  5, 41, :_reduce_37,
  2, 42, :_reduce_38,
  3, 42, :_reduce_39,
  1, 43, :_reduce_40,
  3, 43, :_reduce_41,
  0, 44, :_reduce_42,
  3, 44, :_reduce_43,
  3, 45, :_reduce_44 ]

racc_reduce_n = 45

racc_shift_n = 85

racc_token_table = {
  false => 0,
  :error => 1,
  "*" => 2,
  "/" => 3,
  "+" => 4,
  "-" => 5,
  "=" => 6,
  "def" => 7,
  :IDENTIFIER => 8,
  "(" => 9,
  ")" => 10,
  "end" => 11,
  "," => 12,
  "if" => 13,
  "while" => 14,
  "%" => 15,
  ">" => 16,
  "<" => 17,
  "==" => 18,
  :NUMBER => 19,
  :STRING => 20,
  "[" => 21,
  "]" => 22,
  "]=" => 23,
  "{" => 24,
  "}" => 25,
  "=>" => 26 }

racc_nt_base = 27

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\"=\"",
  "\"def\"",
  "IDENTIFIER",
  "\"(\"",
  "\")\"",
  "\"end\"",
  "\",\"",
  "\"if\"",
  "\"while\"",
  "\"%\"",
  "\">\"",
  "\"<\"",
  "\"==\"",
  "NUMBER",
  "STRING",
  "\"[\"",
  "\"]\"",
  "\"]=\"",
  "\"{\"",
  "\"}\"",
  "\"=>\"",
  "$start",
  "stmts",
  "stmt",
  "func_def",
  "if_stmt",
  "while_stmt",
  "expr",
  "arg_vars",
  "literal",
  "var_ref",
  "var_assign",
  "func_call",
  "ary_new",
  "ary_ref",
  "ary_assign",
  "hash_new",
  "exprs",
  "pairs",
  "pair" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parse.y', 10)
  def _reduce_1(val, _values)
                  ["stmts", val.fetch(0)]
            
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 14)
  def _reduce_2(val, _values)
                  ["stmts", *val.fetch(0)[1..-1], val.fetch(1)]
            
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 17)
  def _reduce_3(val, _values)
     val.fetch(0) 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 18)
  def _reduce_4(val, _values)
     val.fetch(0) 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 19)
  def _reduce_5(val, _values)
     val.fetch(0) 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 20)
  def _reduce_6(val, _values)
     val.fetch(0) 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 24)
  def _reduce_7(val, _values)
                     ["func_def", val.fetch(1), val.fetch(3), val.fetch(3)]
               
  end
.,.,

# reduce 8 omitted

module_eval(<<'.,.,', 'parse.y', 30)
  def _reduce_9(val, _values)
                     val.fetch(0) + [val.fetch(2)]
               
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 35)
  def _reduce_10(val, _values)
                    ["if", val.fetch(1), val.fetch(2)]
              
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 40)
  def _reduce_11(val, _values)
                       ["while", val.fetch(1), val.fetch(2)]
                 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 43)
  def _reduce_12(val, _values)
     val.fetch(0) 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 44)
  def _reduce_13(val, _values)
     val.fetch(0) 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 45)
  def _reduce_14(val, _values)
     val.fetch(0) 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 46)
  def _reduce_15(val, _values)
     val.fetch(0) 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 47)
  def _reduce_16(val, _values)
     val.fetch(0) 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 48)
  def _reduce_17(val, _values)
     val.fetch(0) 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 49)
  def _reduce_18(val, _values)
     val.fetch(0) 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 50)
  def _reduce_19(val, _values)
     val.fetch(0) 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 51)
  def _reduce_20(val, _values)
     [val.fetch(1), val.fetch(0), val.fetch(2)] 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 52)
  def _reduce_21(val, _values)
     [val.fetch(1), val.fetch(0), val.fetch(2)] 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 53)
  def _reduce_22(val, _values)
     [val.fetch(1), val.fetch(0), val.fetch(2)] 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 54)
  def _reduce_23(val, _values)
     [val.fetch(1), val.fetch(0), val.fetch(2)] 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 55)
  def _reduce_24(val, _values)
     [val.fetch(1), val.fetch(0), val.fetch(2)] 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 56)
  def _reduce_25(val, _values)
     [val.fetch(1), val.fetch(0), val.fetch(2)] 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 57)
  def _reduce_26(val, _values)
     [val.fetch(1), val.fetch(0), val.fetch(2)] 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 58)
  def _reduce_27(val, _values)
     [val.fetch(1), val.fetch(0), val.fetch(2)] 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 62)
  def _reduce_28(val, _values)
                    ["lit", val.fetch(0)]
              
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 66)
  def _reduce_29(val, _values)
                    ["lit", val.fetch(0)]
              
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 71)
  def _reduce_30(val, _values)
                    ["var_ref", val.fetch(0)]
              
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 76)
  def _reduce_31(val, _values)
                       ["var_assign", val.fetch(0), val.fetch(2)]
                 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 81)
  def _reduce_32(val, _values)
                      ["func_call", val.fetch(0), []]
                
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 86)
  def _reduce_33(val, _values)
                      ["func_call", val.fetch(0), val.fetch(2)]
                
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 91)
  def _reduce_34(val, _values)
                    ["ary_new", []]
              
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 95)
  def _reduce_35(val, _values)
                    ["ary_new", val.fetch(1)]
              
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 100)
  def _reduce_36(val, _values)
                    ["ary_ref", val.fetch(0), val.fetch(2)]
              
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 105)
  def _reduce_37(val, _values)
                       ["ary_assign", val.fetch(0), val.fetch(2), val.fetch(5)]
                 
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 110)
  def _reduce_38(val, _values)
                     ["hash_new", []]
               
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 114)
  def _reduce_39(val, _values)
                     ["hash_new", val.fetch(1)]
               
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 119)
  def _reduce_40(val, _values)
                  val.fetch(0)
            
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 123)
  def _reduce_41(val, _values)
                  val.fetch(2) + [val.fetch(0)]
            
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 128)
  def _reduce_42(val, _values)
                  val.fetch(0)
            
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 132)
  def _reduce_43(val, _values)
                  val.fetch(0) + val.fetch(2)
            
  end
.,.,

module_eval(<<'.,.,', 'parse.y', 137)
  def _reduce_44(val, _values)
                 [val.fetch(0), val.fetch(2)]
           
  end
.,.,

def _reduce_none(val, _values)
  val[0]
end

end   # class Parser
